### ISSUE TITLE
Manjaro considered harmful, please use something like Alpine.

### ISSUE THREAD

**Issue by eepykate** [liabri/dots#1]

**Comment by liabri** [comment]
System has successfully been moved to arch around a year ago

**Comment by eepykate** [comment]
I do not remember the context of this issue at all.

I wouldn't recommend alpine outside of specific circumstances so I don't think this is just a normal cringe issue.

**Comment by liabri** [comment]
yes it was indeed a joke, but I wanted to close my first issue x)

**Comment by eepykate** [comment]
I was moreso confused about why I made it in the first place.
